<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../public/css/home.css">
    <title>Home</title>
</head>
<body>
    <div id="container">
        <h1>Create your own voting</h1>
        <input type="number" id="num-fields" placeholder="How many fields?">
        <button id="btn">Send</button>
        <div id="form">
            <form action="/create" method="post" id="fields"></form>
        </div>
        <?php if(isset($error)) { ?>
            <p id="error"><?= $error ?></p>
            <button id="btn-try-again"><a href="/">Try again</a></button>
       <?php } ?>
        
    </div>

    <script src="../../public/js/main.js"></script>
</body>
</html>