<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vote</title>
    <link rel="stylesheet" href="../../public/css/votePage.css">
</head>
<body>
    <div id="container">
    
    <a href="/vote?id=1" class="vote">Vote for Candidate 1</a>
    <a href="/vote?id=2"class="vote">Vote for Candidate 2</a>
    <a href="/vote?id=3"class="vote">Vote for Candidate 3</a>
    
    </div>

</body>
</html>