<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vote</title>
    <link rel="stylesheet" href="../../public/css/votePage.css">
</head>
<body>
    <div id="container">

    <?php for($i = 0; $i< count($fields['id']); $i++) { ?>
        <a href="/vote?id=<?=$fields['id'][$i]?>">Vote for <?= $fields['fields'][$i] ?></a>
   <?php } ?>
    
    
    </div>

</body>
</html>