<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../public/css/startVotePage.css">
    <title>Document</title>
</head>
<body>
    <div id="container">
    <h1>Start voting!</h1>
    <button id="btn"><a href="/votePage"> Start!</a></button>
    </div>
</body>
</html>